insert into public.clues(text,difficulty,category,expected_objects,order_group) values
('Find something used to clean a room.','easy','home','["broom","mop","vacuum","duster"]',1),
('Find an object used to connect two electronic devices.','easy','technology','["cable","adapter","connector"]',1),
('Find something capable of producing light.','easy','everyday','["lamp","flashlight","bulb"]',1),
('Find something used to store liquid.','easy','everyday','["bottle","cup","jug"]',1),
('Find something used for writing.','easy','stationery','["pen","pencil","marker"]',1),
('Find something that displays visual information.','easy','technology','["screen","monitor","display"]',1),
('Find something used to tell time.','easy','everyday','["clock","watch","timer"]',2),
('Find an object with wheels.','easy','movement','["chair","cart","bicycle"]',2),
('Find something that can be opened and closed.','easy','everyday','["door","box","drawer"]',2),
('Find an object used for eating.','easy','food','["spoon","fork","chopsticks"]',2),
('Find something soft enough to fold.','easy','materials','["cloth","towel","paper"]',2),
('Find an object with a handle.','easy','everyday','["mug","bag","door"]',2),
('Find something that helps measure a quantity.','medium','measurement','["ruler","scale","measuring cup"]',3),
('Find an object made from at least two materials.','medium','materials','["shoe","chair","phone"]',3),
('Find something whose function depends on electricity.','medium','technology','["computer","fan","charger"]',3),
('Find an object used to organize information.','medium','organization','["notebook","folder","whiteboard"]',3),
('Find an object that can produce sound.','medium','audio','["speaker","bell","instrument"]',3),
('Find something used to protect another object.','medium','protection','["case","cover","helmet"]',3),
('Find something that has a repeating pattern.','medium','visual','["fabric","tile","wallpaper"]',4),
('Find an object with more than one moving part.','medium','mechanical','["scissors","stapler","bicycle"]',4),
('Find something designed to save space.','medium','design','["folding chair","stackable box"]',4),
('Find an object that uses reflection.','medium','science','["mirror","reflector","periscope"]',4),
('Find something that changes shape when used.','medium','materials','["sponge","spring","rubber band"]',4),
('Find an object that guides movement.','medium','navigation','["sign","rail","track"]',4),
('Find an object whose purpose is not obvious from appearance alone.','hard','reasoning','[]',5),
('Find something that demonstrates human-computer interaction.','hard','technology','["keyboard","touchscreen","mouse"]',5),
('Find an object that functions as an input device.','hard','technology','["keyboard","microphone","camera"]',5),
('Find an object whose meaning changes depending on context.','hard','semantics','["sign","symbol","badge"]',5),
('Find something that uses or contains a sensor.','hard','technology','["phone","thermostat","camera"]',5),
('Find something that transforms one type of energy into another.','hard','science','["motor","speaker","solar panel"]',5),
('Find an object designed around a human limitation.','hard','design','["glasses","hearing aid","ramp"]',6),
('Find something that communicates without words.','hard','communication','["traffic light","gesture icon","alarm"]',6),
('Find an object with a hidden mechanism.','hard','mechanical','["lock","automatic door","stapler"]',6),
('Find something whose value depends on shared agreement.','hard','culture','["money","ticket","certificate"]',6),
('Find an object that reduces friction in a process.','hard','systems','["wheel","bearing","form"]',6),
('Find something that stores information without electricity.','hard','information','["book","barcode","label"]',6)
on conflict(text) do update set difficulty=excluded.difficulty, category=excluded.category, expected_objects=excluded.expected_objects, order_group=excluded.order_group;
