"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, LoaderCircle, LogOut, Plus } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";
import { NeoButton, NeoCard, StatusBadge } from "./neo";

type Room = { id:string; name:string; code:string; status:string; maximum_teams:number; game_duration_seconds:number; leaderboard_visible_seconds:number; created_at:string };
export function RoomManager() {
  const [rooms,setRooms]=useState<Room[]>([]); const [showForm,setShowForm]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function load(){ const res=await fetch("/api/admin/rooms",{cache:"no-store"}); if(res.status===401){location.href="/admin/login";return;} const data=await res.json(); if(res.ok)setRooms(data.rooms);else setError(data.error); }
  useEffect(()=>{void load();},[]);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const payload={name:form.get("name"),code:form.get("code"),maximumTeams:form.get("maximumTeams"),gameDurationMinutes:form.get("duration"),leaderboardVisibleMinutes:form.get("leaderboard"),clueProgressionStrategy:form.get("strategy"),endingTitle:form.get("endingTitle"),endingMessage:form.get("endingMessage"),meetingLocation:form.get("location"),finalLeaderboardVisible:false};const res=await fetch("/api/admin/rooms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)setError(data.error);else{setShowForm(false);await load();}setBusy(false);}
  async function logout(){await getSupabaseBrowserClient()?.auth.signOut();location.href="/admin/login";}
  return <><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="kicker">Mission control</p><h1 className="display mt-2 text-5xl">Game rooms</h1></div><div className="flex gap-3"><button onClick={logout} className="secondary-button"><LogOut size={17}/>Sign out</button><NeoButton onClick={()=>setShowForm(!showForm)}><Plus/>New room</NeoButton></div></div>{showForm&&<NeoCard className="mt-8 bg-kcv-yellow p-6"><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><Field name="name" label="Room name" placeholder="KCV Summer Hunt"/><Field name="code" label="Room code" placeholder="KCV26"/><Field name="maximumTeams" label="Maximum teams" type="number" defaultValue="20"/><Field name="duration" label="Total duration (minutes)" type="number" defaultValue="30"/><Field name="leaderboard" label="Leaderboard visible (minutes)" type="number" defaultValue="20"/><label><span className="field-label">Progression</span><select className="neo-input" name="strategy" defaultValue="easy_to_hard"><option value="easy_to_hard">Easy to hard</option><option value="random">Random</option></select></label><Field name="endingTitle" label="Ending title" defaultValue="It ended…"/><Field name="location" label="Meeting location" placeholder="Plaza Supeno"/><label className="md:col-span-2"><span className="field-label">Ending message</span><textarea className="neo-input min-h-24" name="endingMessage" defaultValue="Great hunting. The winner will be announced soon."/></label><div className="md:col-span-2 flex justify-end"><NeoButton disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Plus/>}Create room</NeoButton></div></form></NeoCard>}<p className="mt-4 min-h-5 text-sm font-bold text-red-700">{error}</p><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rooms.map(room=><Link key={room.id} href={`/admin/rooms/${room.id}`}><NeoCard className="group h-full p-6 transition-transform hover:-translate-y-1"><div className="flex justify-between"><StatusBadge tone={room.status==="active"?"green":room.status==="ended"?"red":"orange"}>{room.status}</StatusBadge><ArrowRight className="transition-transform group-hover:translate-x-1"/></div><h2 className="display mt-7 text-3xl">{room.name}</h2><p className="mt-1 font-mono text-sm tracking-widest">{room.code}</p><div className="mt-8 grid grid-cols-2 gap-3 border-t border-zinc-300 pt-4 text-xs"><span>{room.game_duration_seconds/60} min game</span><span>{room.leaderboard_visible_seconds/60} min public board</span></div></NeoCard></Link>)}{!rooms.length&&!showForm&&<div className="col-span-full border-2 border-dashed border-zinc-400 p-12 text-center text-zinc-500">No rooms yet. Create one to start hunting.</div>}</div></>;
}
function Field({label,...props}:{label:string;name:string;type?:string;placeholder?:string;defaultValue?:string}){return <label><span className="field-label">{label}</span><input className="neo-input" required {...props}/></label>}
